# ??, ???? ????
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show-sql: true ??????? ??????? ???? ??? ????
        format_sql: true
        default_batch_fetch_size: 100 # ????? ????? 100?? ??, max ?? ??? DB in ??? ??? ?? ??? ????? ??? ????? -> DB ??? ?? ?? ?? ??
        # ??? 100 ~1000 ??? ??? 1000?? ??? ?????? in ?? 1000?? ????? ? ???? ??? ?? ??? ?? ?? ??? ?? ??? ??? ?? ?? ??
        # Was ? DB ? ?? ? ??? ? ??? ?? -> ?? ??? ??? 100?? ?? ???? ?????
    open-in-view: false
#spring.io.docs?? ?????
logging:
  level:
    org.hibernate.SQL: debug

#spring.jpa.open-in-view : false
# spring.jpa.open-in-view is enabled by default. warn ?? ? ???? true ?
# ????? ????? ???? ???? ???? ???? ?? ???? ??????, ?????? ???????? ????.
# ?? ???? ?? ?? ?? ?? ??? ??? ???? ??? ????????? ??? ??? ? ??.
# "org.hibernate.LazyInitializationException: could not initialize proxy [jpabook.jpashop.domain.Member#1] - no Session\n\tat org.hibernate.proxy
# ? ??? ????? ???? ?? ??????? ??? ?? ????? ???? ??? ????.
# ???? ???? ??? ??? ?????
# ???? 1. ?? ??? ???? ??? ????. 2. open-in-view ? true ? ????. 3. ????? ??