# ??, ???? ????
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show-sql: true ??????? ??????? ???? ??? ????
        format_sql: true
#spring.io.docs?? ?????
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.jdbc.bind: trace

#spring.jpa.open-in-view : false
